version: '3.7'

services:
  database:
    image: postgres
    container_name: database_terms
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=termsdatabase
      - POSTGRES_DB=termsDb
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    command: sh -c "npx prisma migrate dev && npm run dev"
    container_name: terms
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local